"""baseline schema

Revision ID: 71f5e126461a
Revises:
Create Date: 2026-09-16 21:33:21.117797
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "71f5e126461a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guard_accounts",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("account_id", sa.String(length=40), nullable=False),
        sa.Column("owner_subject", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fee_cents", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "account_id"),
    )
    op.create_table(
        "guard_actions",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("operation_id", sa.String(length=32), nullable=False),
        sa.Column("conversation_id", sa.String(length=32), nullable=False),
        sa.Column("arguments", sa.Text(), nullable=False),
        sa.Column("arguments_digest", sa.String(length=64), nullable=False),
        sa.Column("account_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("receipt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("guard_actions", schema=None) as batch_op:
        batch_op.create_index(
            "guard_one_mutation_per_operation", ["tenant_id", "subject", "operation_id"], unique=True
        )

    op.create_table(
        "guard_audit",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("key_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("signature", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "event_id"),
    )
    with op.batch_alter_table("guard_audit", schema=None) as batch_op:
        batch_op.create_index("guard_audit_created", ["tenant_id", "created_at"], unique=False)
        batch_op.create_index("guard_audit_sequence", ["tenant_id", "sequence"], unique=True)

    op.create_table(
        "guard_audit_heads",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column("last_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "guard_audit_outbox",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("envelope", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("exported_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("tenant_id", "event_id"),
    )
    with op.batch_alter_table("guard_audit_outbox", schema=None) as batch_op:
        batch_op.create_index("guard_outbox_pending", ["state", "created_at"], unique=False)

    op.create_table(
        "guard_conversations",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_table(
        "guard_document_roles",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("doc_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "doc_id", "role"),
    )
    op.create_table(
        "guard_documents",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("doc_id", sa.String(length=128), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("owner_subject", sa.String(length=128), nullable=True),
        sa.Column("conversation_id", sa.String(length=32), nullable=True),
        sa.Column("upload_state", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("retention_policy", sa.String(length=128), nullable=False),
        sa.Column("provenance_verified", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "doc_id"),
    )
    op.create_table(
        "guard_operations",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("operation_id", sa.String(length=32), nullable=False),
        sa.Column("conversation_id", sa.String(length=32), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("output_doc_ids", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "subject", "operation_id"),
    )
    op.create_table(
        "guard_quotas",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("dimension", sa.String(length=32), nullable=False),
        sa.Column("bucket", sa.Integer(), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "subject", "dimension", "bucket"),
    )
    op.create_table(
        "guard_security_cases",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=True),
        sa.Column("actor_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guard_security_cases")
    op.drop_table("guard_quotas")
    op.drop_table("guard_operations")
    op.drop_table("guard_documents")
    op.drop_table("guard_document_roles")
    op.drop_table("guard_conversations")
    with op.batch_alter_table("guard_audit_outbox", schema=None) as batch_op:
        batch_op.drop_index("guard_outbox_pending")

    op.drop_table("guard_audit_outbox")
    op.drop_table("guard_audit_heads")
    with op.batch_alter_table("guard_audit", schema=None) as batch_op:
        batch_op.drop_index("guard_audit_sequence")
        batch_op.drop_index("guard_audit_created")

    op.drop_table("guard_audit")
    with op.batch_alter_table("guard_actions", schema=None) as batch_op:
        batch_op.drop_index("guard_one_mutation_per_operation")

    op.drop_table("guard_actions")
    op.drop_table("guard_accounts")
    # ### end Alembic commands ###
